version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 10.x
      python: 3.x  
    commands:
      - npm install
      - npm install -g serverless
      - pip install --upgrade pip
  build:
    commands:
      - serverless deploy --stage cicd | tee deploy.out
  post_build:
    commands:
      # - . ./test.sh